
Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.box_version = "1905.01"

  config.vm.network "forwarded_port", guest: 9080, host: 9080
  #config.vm.synced_folder ".", "/downloads", type:"smb"

  # Provider-specific configuration so you can fine-tune various
  config.vm.provider "hyperv" do |hyper|
	hyper.vmname = "webgoat_training"
	hyper.memory = "4096"
	hyper.cpus = 2
	#hyper.gui = true
   end

   config.vm.provision "shell", path: "provision.sh", privileged: false

end
