Vagrant.configure("2") do |config|
	config.vm.box = "owaspwebgoat/training"
	config.vm.box_version = "20.0.0"
	#config.vm.network "forwarded_port", guest: 8080, host: 8080

	config.vm.provider "virtualbox" do |vb|
		vb.name = "webgoat_training"
		vb.memory = "4096"
		vb.cpus = 2
		vb.gui = true
	end
end